name: chenille

version: '3.8'

services:
  postgres:
    container_name: chenille_postgres
    image: docker.1ms.run/postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: chenille
      POSTGRES_USER: chenille
      POSTGRES_PASSWORD: dE4kL3xT6gI1hT4eQ1cP2iV7iK4jQ6sK
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --lc-collate=C --lc-ctype=C'
      TZ: Asia/Shanghai
    ports:
      - '15432:5432'
    volumes:
      - /docker/volumes/chenille/postgres/db_back:/db_back
      - /docker/volumes/chenille/postgres/data:/var/lib/postgresql/data
    networks:
      - chenille_network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U chenille -d chenille']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    container_name: chenille_redis
    restart: unless-stopped
    image: docker.1ms.run/redis:7-alpine
    command: redis-server --appendonly yes
    ports:
      - '16379:6379'
    volumes:
      - /docker/volumes/chenille/redis/data:/data
      - /docker/volumes/chenille/redis/logs:/var/log/redis
    environment:
      - TZ=Asia/Shanghai
    networks:
      - chenille_network
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 3s
      retries: 5

  # chenille:
  #   container_name: chenille
  #   restart: unless-stopped
  #   image: chenille:1.0.0
  #   ports:
  #     - '13000:13000'
  #   env_file:
  #     - .env
  #   networks:
  #     - chenille_network

networks:
  chenille_network:
    driver: bridge
